# 4.8 Grouping Data and Aggregating Variables

1. Aggregating data with agg() function
2. Aggregating data with transform()
3. Deriving columns with loc()

In [1]:
#import libraries
import pandas as pd
import numpy as np
import os

In [2]:
#create usable path 
path = r'C:\Users\rutha\CareerFoundry\01-23_Instacart_Basket_Analysis'

In [3]:
#import dataframe
df = pd.read_pickle(os.path.join(path, '02_Data', 'Prepared_data', 'full_merged3.pkl'))

In [4]:
#dropping busiest day column
df = df.drop(['busiest_day'], axis = 1)

In [5]:
df.head()

,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,_merge,product_name,aisle_id,department_id,prices,price_range_loc,busiest_days,busiest_period_of_day
0,2539329,1,1,2,8,NaN,196,1,0,both,Soda,77.0,7.0,9.0,Mid-range product,Regularly busy,Average orders
1,2539329,1,1,2,8,NaN,14084,2,0,both,Organic Unsweetened Vanilla Almond Milk,91.0,16.0,12.5,Mid-range product,Regularly busy,Average orders
2,2539329,1,1,2,8,NaN,12427,3,0,both,Original Beef Jerky,23.0,19.0,4.4,Low-range product,Regularly busy,Average orders
3,2539329,1,1,2,8,NaN,26088,4,0,both,Aged White Cheddar Popcorn,23.0,19.0,4.7,Low-range product,Regularly busy,Average orders
4,2539329,1,1,2,8,NaN,26405,5,0,both,XL Pick-A-Size Paper Towel Rolls,54.0,17.0,1.0,Low-range product,Regularly busy,Average orders

Create a subset of the first one million entries in the dataframe

In [6]:
#create subset of first one million entries
df_subset = df[:1000000]

print('Sample output of subset filter of merged dataset:')
df_subset.sample(5)

Sample output of subset filter of merged dataset:

,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,_merge,product_name,aisle_id,department_id,prices,price_range_loc,busiest_days,busiest_period_of_day
784621,1804176,5168,27,3,18,2.0,25659,5,1,both,Organic Coconut Milk,91.0,16.0,4.1,Low-range product,Slowest days,Average orders
603219,2333242,4041,11,4,10,15.0,-24639,9,1,both,Kale,123.0,4.0,6.6,Mid-range product,Slowest days,Most orders
43670,1169863,290,13,6,11,7.0,16669,5,1,both,Grilled Chicken Canine Cuisine Wet Dog Food,40.0,8.0,14.0,Mid-range product,Regularly busy,Most orders
80155,2324216,523,2,5,15,16.0,21694,1,1,both,Mini Classic Ice Cream,37.0,1.0,8.9,Mid-range product,Regularly busy,Most orders
369163,3378514,2446,4,6,11,7.0,22935,13,1,both,Organic Yellow Onion,83.0,4.0,1.4,Low-range product,Regularly busy,Most orders

In [7]:
df_subset.shape

(1000000, 17)

# 1. Grouping data with agg() function

In [8]:
#group your data by product name
df.groupby('product_name')

Calculating the mean of the 'order_number' grouped by 'department_id'

In [9]:
#split the data into groups based on dep_id, then agg() by ord_number
df.groupby('department_id').agg({'order_number': ['mean']})

              order_number
                      mean
department_id
1.0              15.457838
2.0              17.277920
3.0              17.170395
4.0              17.811403
5.0              15.215751
6.0              16.439806
7.0              17.225802
8.0              15.340650
9.0              15.895474
10.0             20.197148
11.0             16.170638
12.0             15.887671
13.0             16.583536
14.0             16.773669
15.0             16.165037
16.0             17.665606
17.0             15.694469
18.0             19.310397
19.0             17.177343
20.0             16.473447
21.0             22.902379

In [10]:
#using the mean() function
df.groupby('department_id')['order_number'].mean()

department_id
1.0     15.457838
2.0     17.277920
3.0     17.170395
4.0     17.811403
5.0     15.215751
6.0     16.439806
7.0     17.225802
8.0     15.340650
9.0     15.895474
10.0    20.197148
11.0    16.170638
12.0    15.887671
13.0    16.583536
14.0    16.773669
15.0    16.165037
16.0    17.665606
17.0    15.694469
18.0    19.310397
19.0    17.177343
20.0    16.473447
21.0    22.902379
Name: order_number, dtype: float64

In [11]:
#performing multiple aggregations 

print('The mean, min, and max of order_number grouped by the department_id:')
df.groupby('department_id').agg({'order_number': ['mean', 'min', 'max']})

The mean, min, and max of order_number grouped by the department_id:

              order_number
                      mean min max
department_id
1.0              15.457838   1  99
2.0              17.277920   1  99
3.0              17.170395   1  99
4.0              17.811403   1  99
5.0              15.215751   1  99
6.0              16.439806   1  99
7.0              17.225802   1  99
8.0              15.340650   1  99
9.0              15.895474   1  99
10.0             20.197148   1  99
11.0             16.170638   1  99
12.0             15.887671   1  99
13.0             16.583536   1  99
14.0             16.773669   1  99
15.0             16.165037   1  99
16.0             17.665606   1  99
17.0             15.694469   1  99
18.0             19.310397   1  99
19.0             17.177343   1  99
20.0             16.473447   1  99
21.0             22.902379   1  99

# 2. Aggregating Data with Transform

In [12]:
df['max_order'] = df.groupby(['user_id'])['order_number'].transform(np.max)

In [13]:
#function to display all rows
pd.options.display.max_rows = None

In [14]:
df.head(100)

,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,_merge,product_name,aisle_id,department_id,prices,price_range_loc,busiest_days,busiest_period_of_day,max_order
0,2539329,1,1,2,8,NaN,196,1,0,both,Soda,77.0,7.0,9.0,Mid-range product,Regularly busy,Average orders,10
1,2539329,1,1,2,8,NaN,14084,2,0,both,Organic Unsweetened Vanilla Almond Milk,91.0,16.0,12.5,Mid-range product,Regularly busy,Average orders,10
2,2539329,1,1,2,8,NaN,12427,3,0,both,Original Beef Jerky,23.0,19.0,4.4,Low-range product,Regularly busy,Average orders,10
3,2539329,1,1,2,8,NaN,26088,4,0,both,Aged White Cheddar Popcorn,23.0,19.0,4.7,Low-range product,Regularly busy,Average orders,10
4,2539329,1,1,2,8,NaN,26405,5,0,both,XL Pick-A-Size Paper Towel Rolls,54.0,17.0,1.0,Low-range product,Regularly busy,Average orders,10
5,2398795,1,2,3,7,15.0,196,1,1,both,Soda,77.0,7.0,9.0,Mid-range product,Slowest days,Average orders,10
6,2398795,1,2,3,7,15.0,10258,2,0,both,Pistachios,117.0,19.0,3.0,Low-range product,Slowest days,Average orders,10
7,2398795,1,2,3,7,15.0,12427,3,1,both,Original Beef Jerky,23.0,19.0,4.4,Low-range product,Slowest days,Average orders,10
8,2398795,1,2,3,7,15.0,13176,4,0,both,Bag of Organic Bananas,24.0,4.0,10.3,Mid-range product,Slowest days,Average orders,10
9,2398795,1,2,3,7,15.0,26088,5,1,both,Aged White Cheddar Popcorn,23.0,19.0,4.7,Low-range product,Slowest days,Average orders,10
10,2398795,1,2,3,7,15.0,13032,6,0,both,Cinnamon Toast Crunch,121.0,14.0,4.0,Low-range product,Slowest days,Average orders,10
11,473747,1,3,3,12,21.0,196,1,1,both,Soda,77.0,7.0,9.0,Mid-range product,Slowest days,Most orders,10
12,473747,1,3,3,12,21.0,12427,2,1,both,Original Beef Jerky,23.0,19.0,4.4,Low-range product,Slowest days,Most orders,10
13,473747,1,3,3,12,21.0,10258,3,1,both,Pistachios,117.0,19.0,3.0,Low-range product,Slowest days,Most orders,10
14,473747,1,3,3,12,21.0,25133,4,0,both,Organic String Cheese,21.0,16.0,8.6,Mid-range product,Slowest days,Most orders,10
15,473747,1,3,3,12,21.0,30450,5,0,both,Creamy Almond Butter,88.0,13.0,3.2,Low-range product,Slowest days,Most orders,10
16,2254736,1,4,4,7,29.0,196,1,1,both,Soda,77.0,7.0,9.0,Mid-range product,Slowest days,Average orders,10
17,2254736,1,4,4,7,29.0,12427,2,1,both,Original Beef Jerky,23.0,19.0,4.4,Low-range product,Slowest days,Average orders,10
18,2254736,1,4,4,7,29.0,10258,3,1,both,Pistachios,117.0,19.0,3.0,Low-range product,Slowest days,Average orders,10
19,2254736,1,4,4,7,29.0,25133,4,1,both,Organic String Cheese,21.0,16.0,8.6,Mid-range product,Slowest days,Average orders,10
20,2254736,1,4,4,7,29.0,26405,5,1,both,XL Pick-A-Size Paper Towel Rolls,54.0,17.0,1.0,Low-range product,Slowest days,Average orders,10
21,431534,1,5,4,15,28.0,196,1,1,both,Soda,77.0,7.0,9.0,Mid-range product,Slowest days,Most orders,10
22,431534,1,5,4,15,28.0,12427,2,1,both,Original Beef Jerky,23.0,19.0,4.4,Low-range product,Slowest days,Most orders,10
23,431534,1,5,4,15,28.0,10258,3,1,both,Pistachios,117.0,19.0,3.0,Low-range product,Slowest days,Most orders,10
24,431534,1,5,4,15,28.0,25133,4,1,both,Organic String Cheese,21.0,16.0,8.6,Mid-range product,Slowest days,Most orders,10
25,431534,1,5,4,15,28.0,10326,5,0,both,Organic Fuji Apples,24.0,4.0,2.7,Low-range product,Slowest days,Most orders,10
26,431534,1,5,4,15,28.0,17122,6,0,both,Honeycrisp Apples,24.0,4.0,14.0,Mid-range product,Slowest days,Most orders,10
27,431534,1,5,4,15,28.0,-23749,7,0,both,Bartlett Pears,24.0,4.0,5.0,Low-range product,Slowest days,Most orders,10
28,431534,1,5,4,15,28.0,13176,8,1,both,Bag of Organic Bananas,24.0,4.0,10.3,Mid-range product,Slowest days,Most orders,10
29,3367565,1,6,2,7,19.0,196,1,1,both,Soda,77.0,7.0,9.0,Mid-range product,Regularly busy,Average orders,10
30,3367565,1,6,2,7,19.0,12427,2,1,both,Original Beef Jerky,23.0,19.0,4.4,Low-range product,Regularly busy,Average orders,10
31,3367565,1,6,2,7,19.0,10258,3,1,both,Pistachios,117.0,19.0,3.0,Low-range product,Regularly busy,Average orders,10
32,3367565,1,6,2,7,19.0,25133,4,1,both,Organic String Cheese,21.0,16.0,8.6,Mid-range product,Regularly busy,Average orders,10
33,550135,1,7,1,9,20.0,196,1,1,both,Soda,77.0,7.0,9.0,Mid-range product,Busiest days,Most orders,10
34,550135,1,7,1,9,20.0,10258,2,1,both,Pistachios,117.0,19.0,3.0,Low-range product,Busiest days,Most orders,10
35,550135,1,7,1,9,20.0,12427,3,1,both,Original Beef Jerky,23.0,19.0,4.4,Low-range product,Busiest days,Most orders,10
36,550135,1,7,1,9,20.0,25133,4,1,both,Organic String Cheese,21.0,16.0,8.6,Mid-range product,Busiest days,Most orders,10
37,550135,1,7,1,9,20.0,13032,5,1,both,Cinnamon Toast Crunch,121.0,14.0,4.0,Low-range product,Busiest days,Most orders,10
38,3108588,1,8,1,14,14.0,12427,1,1,both,Original Beef Jerky,23.0,19.0,4.4,Low-range product,Busiest days,Most orders,10
39,3108588,1,8,1,14,14.0,196,2,1,both,Soda,77.0,7.0,9.0,Mid-range product,Busiest days,Most orders,10
40,3108588,1,8,1,14,14.0,10258,3,1,both,Pistachios,117.0,19.0,3.0,Low-range product,Busiest days,Most orders,10
41,3108588,1,8,1,14,14.0,25133,4,1,both,Organic String Cheese,21.0,16.0,8.6,Mid-range product,Busiest days,Most orders,10
42,3108588,1,8,1,14,14.0,-19387,5,0,both,Zero Calorie Cola,77.0,7.0,13.4,Mid-range product,Busiest days,Most orders,10
43,3108588,1,8,1,14,14.0,-16301,6,0,both,Organic Half & Half,53.0,16.0,1.8,Low-range product,Busiest days,Most orders,10
44,2295261,1,9,1,16,0.0,-16301,1,1,both,Organic Half & Half,53.0,16.0,1.8,Low-range product,Busiest days,Most orders,10
45,2295261,1,9,1,16,0.0,-19387,2,1,both,Zero Calorie Cola,77.0,7.0,13.4,Mid-range product,Busiest days,Most orders,10
46,2295261,1,9,1,16,0.0,25133,3,1,both,Organic String Cheese,21.0,16.0,8.6,Mid-range product,Busiest days,Most orders,10
47,2295261,1,9,1,16,0.0,196,4,1,both,Soda,77.0,7.0,9.0,Mid-range product,Busiest days,Most orders,10
48,2295261,1,9,1,16,0.0,10258,5,1,both,Pistachios,117.0,19.0,3.0,Low-range product,Busiest days,Most orders,10
49,2295261,1,9,1,16,0.0,12427,6,1,both,Original Beef Jerky,23.0,19.0,4.4,Low-range product,Busiest days,Most orders,10
50,2550362,1,10,4,8,30.0,196,1,1,both,Soda,77.0,7.0,9.0,Mid-range product,Slowest days,Average orders,10
51,2550362,1,10,4,8,30.0,-19387,2,1,both,Zero Calorie Cola,77.0,7.0,13.4,Mid-range product,Slowest days,Average orders,10
52,2550362,1,10,4,8,30.0,-25879,3,0,both,Milk Chocolate Almonds,45.0,19.0,6.8,Mid-range product,Slowest days,Average orders,10
53,2550362,1,10,4,8,30.0,-26608,4,0,both,0% Greek Strained Yogurt,120.0,16.0,12.6,Mid-range product,Slowest days,Average orders,10
54,2550362,1,10,4,8,30.0,25133,5,1,both,Organic String Cheese,21.0,16.0,8.6,Mid-range product,Slowest days,Average orders,10
55,2550362,1,10,4,8,30.0,10258,6,1,both,Pistachios,117.0,19.0,3.0,Low-range product,Slowest days,Average orders,10
56,2550362,1,10,4,8,30.0,-29585,7,0,both,Organic Unsweetened Almond Milk,91.0,16.0,1.3,Low-range product,Slowest days,Average orders,10
57,2550362,1,10,4,8,30.0,13032,8,1,both,Cinnamon Toast Crunch,121.0,14.0,4.0,Low-range product,Slowest days,Average orders,10
58,2550362,1,10,4,8,30.0,12427,9,1,both,Original Beef Jerky,23.0,19.0,4.4,Low-range product,Slowest days,Average orders,10
59,2168274,2,1,2,11,NaN,-32744,1,0,both,Chipotle Beef & Pork Realstick,23.0,19.0,5.2,Mid-range product,Regularly busy,Most orders,14
60,2168274,2,1,2,11,NaN,-17770,2,0,both,Organic Avocado,24.0,4.0,6.3,Mid-range product,Regularly busy,Most orders,14
61,2168274,2,1,2,11,NaN,20574,3,0,both,Roasted Turkey,96.0,20.0,2.3,Low-range product,Regularly busy,Most orders,14
62,2168274,2,1,2,11,NaN,12000,4,0,both,Baked Organic Sea Salt Crunchy Pea Snack,72.0,13.0,10.9,Mid-range product,Regularly busy,Most orders,14
63,2168274,2,1,2,11,NaN,-17426,5,0,both,Thin Stackers Brown Rice Lightly Salted,78.0,19.0,2.7,Low-range product,Regularly busy,Most orders,14
64,2168274,2,1,2,11,NaN,22474,6,0,both,Cheddar Bunnies Snack Crackers,78.0,19.0,4.1,Low-range product,Regularly busy,Most orders,14
65,2168274,2,1,2,11,NaN,16589,7,0,both,Plantain Chips,107.0,19.0,5.0,Low-range product,Regularly busy,Most orders,14
66,2168274,2,1,2,11,NaN,-29619,8,0,both,Organic Just Concord Grape Juice,98.0,7.0,9.4,Mid-range product,Regularly busy,Most orders,14
67,2168274,2,1,2,11,NaN,27344,9,0,both,Uncured Genoa Salami,96.0,20.0,14.8,Mid-range product,Regularly busy,Most orders,14
68,2168274,2,1,2,11,NaN,30489,10,0,both,Original Hummus,67.0,20.0,7.5,Mid-range product,Regularly busy,Most orders,14
69,2168274,2,1,2,11,NaN,27966,11,0,both,Organic Raspberries,123.0,4.0,4.4,Low-range product,Regularly busy,Most orders,14
70,2168274,2,1,2,11,NaN,13176,12,0,both,Bag of Organic Bananas,24.0,4.0,10.3,Mid-range product,Regularly busy,Most orders,14
71,2168274,2,1,2,11,NaN,-20470,13,0,both,Honeycrisp Apple,24.0,4.0,2.5,Low-range product,Regularly busy,Most orders,14
72,1501582,2,2,5,10,10.0,16797,1,0,both,Strawberries,24.0,4.0,1.3,Low-range product,Regularly busy,Most orders,14
73,1501582,2,2,5,10,10.0,-18010,2,0,both,Goat Cheese Log,21.0,16.0,2.0,Low-range product,Regularly busy,Most orders,14
74,1501582,2,2,5,10,10.0,8479,3,0,both,Original Black Box Tablewater Cracker,78.0,19.0,3.5,Low-range product,Regularly busy,Most orders,14
75,1501582,2,2,5,10,10.0,-17770,4,1,both,Organic Avocado,24.0,4.0,6.3,Mid-range product,Regularly busy,Most orders,14
76,1501582,2,2,5,10,10.0,19051,5,0,both,"Pita Chips, Simply Naked, Party Size",107.0,19.0,3.9,Low-range product,Regularly busy,Most orders,14
77,1501582,2,2,5,10,10.0,8138,6,0,both,Traditional Hummus,67.0,20.0,2.0,Low-range product,Regularly busy,Most orders,14
78,1901567,2,3,1,10,3.0,-17770,1,1,both,Organic Avocado,24.0,4.0,6.3,Mid-range product,Busiest days,Most orders,14
79,1901567,2,3,1,10,3.0,-32744,2,1,both,Chipotle Beef & Pork Realstick,23.0,19.0,5.2,Mid-range product,Busiest days,Most orders,14
80,1901567,2,3,1,10,3.0,20574,3,1,both,Roasted Turkey,96.0,20.0,2.3,Low-range product,Busiest days,Most orders,14
81,1901567,2,3,1,10,3.0,7781,4,0,both,Organic Sticks Low Moisture Part Skim Mozzarel...,21.0,16.0,6.6,Mid-range product,Busiest days,Most orders,14
82,1901567,2,3,1,10,3.0,28874,5,0,both,Carrot Ginger Soup,1.0,20.0,6.2,Mid-range product,Busiest days,Most orders,14
83,738281,2,4,2,10,8.0,-16085,1,0,both,Artichoke Spinach Dip,67.0,20.0,7.1,Mid-range product,Regularly busy,Most orders,14
84,738281,2,4,2,10,8.0,-32744,2,1,both,Chipotle Beef & Pork Realstick,23.0,19.0,5.2,Mid-range product,Regularly busy,Most orders,14
85,738281,2,4,2,10,8.0,32139,3,0,both,Hommus Classic Original,67.0,20.0,7.5,Mid-range product,Regularly busy,Most orders,14
86,738281,2,4,2,10,8.0,-30848,4,0,both,Good Belly Probiotics Juice Drink Blueberry Ac...,31.0,7.0,5.8,Mid-range product,Regularly busy,Most orders,14
87,738281,2,4,2,10,8.0,-28801,5,0,both,Organic Roasted Sliced Chicken Breast,96.0,20.0,8.9,Mid-range product,Regularly busy,Most orders,14
88,738281,2,4,2,10,8.0,-27890,6,0,both,Organic Gala Apples,24.0,4.0,9.1,Mid-range product,Regularly busy,Most orders,14
89,738281,2,4,2,10,8.0,22829,7,0,both,Multigrain Flax Seeded Flatbread Crackers,78.0,19.0,5.5,Mid-range product,Regularly busy,Most orders,14
90,738281,2,4,2,10,8.0,24852,8,0,both,Banana,24.0,4.0,12.3,Mid-range product,Regularly busy,Most orders,14
91,738281,2,4,2,10,8.0,-18327,9,0,both,Organic Hass Avocado,24.0,4.0,4.0,Low-range product,Regularly busy,Most orders,14
92,738281,2,4,2,10,8.0,-32260,10,0,both,Kalamata Olive Spread,67.0,20.0,10.8,Mid-range product,Regularly busy,Most orders,14
93,738281,2,4,2,10,8.0,-19923,11,0,both,Pad Thai,38.0,1.0,12.6,Mid-range product,Regularly busy,Most orders,14
94,738281,2,4,2,10,8.0,9681,12,0,both,Chicken Tikka Masala with Cumin Infused Basmat...,38.0,1.0,2.0,Low-range product,Regularly busy,Most orders,14
95,738281,2,4,2,10,8.0,21150,13,0,both,Fire Grilled Steak Bowl,38.0,1.0,5.9,Mid-range product,Regularly busy,Most orders,14
96,1673511,2,5,3,11,8.0,-18392,1,0,both,Unsweetened Original Almond Breeze Almond Milk,91.0,16.0,14.0,Mid-range product,Slowest days,Most orders,14
97,1673511,2,5,3,11,8.0,5322,2,0,both,Gluten Free Dark Chocolate Chunk Chewy with a ...,3.0,19.0,2.9,Low-range product,Slowest days,Most orders,14
98,1673511,2,5,3,11,8.0,17224,3,0,both,Oats & Honey Gluten Free Granola,3.0,19.0,1.6,Low-range product,Slowest days,Most orders,14
99,1673511,2,5,3,11,8.0,-26880,4,0,both,Gluten Free Peanut Butter Dark Chocolate Chewy...,3.0,19.0,3.4,Low-range product,Slowest days,Most orders,14

# Deriving Columns with loc()

In [15]:
#creating my flag based on values using loc()

In [16]:
df.loc[df['max_order'] > 40, 'loyalty_flag'] = 'Loyal customer'

In [17]:
df.loc[df['max_order'] <= 40, 'loyalty_flag'] = 'Regular customer'

In [18]:
df.loc[df['max_order'] <= 10, 'loyalty_flag'] = 'New customer'

In [19]:
df['loyalty_flag'].value_counts(dropna = False)

Regular customer    15891507
Loyal customer      10294027
New customer         6249525
Name: loyalty_flag, dtype: int64

In [20]:
#checking output of certain columns
df[['user_id', 'loyalty_flag', 'max_order']].sample(60)

          user_id      loyalty_flag  max_order
11885032    75249  Regular customer         11
11104556    70344      New customer          7
27881156   177171  Regular customer         23
13382167    84652    Loyal customer         85
14095958    89247  Regular customer         12
16390029   103672  Regular customer         32
20273069   128648      New customer          9
31982890   203256    Loyal customer         99
16923324   107124  Regular customer         38
26472203   168292      New customer          4
17647093   111593  Regular customer         30
30103164   191261  Regular customer         24
22943851   145695    Loyal customer         57
4613972     29411    Loyal customer         45
18660734   118109      New customer          5
23237551   147534    Loyal customer         69
2861092     18276  Regular customer         35
13153931    83276      New customer          4
6930895     43989    Loyal customer         86
22198539   141003  Regular customer         24
31673427   201283    Loyal customer         64
13708993    86773    Loyal customer         68
26220676   166648      New customer          9
11878469    75192  Regular customer         19
29935707   190207  Regular customer         30
27501345   174814      New customer          3
4898383     31182    Loyal customer         68
31724108   201623    Loyal customer         99
27873224   177124      New customer          7
7589883     48148    Loyal customer         44
13547348    85731    Loyal customer         74
19362896   122692      New customer          6
3771533     23956      New customer          8
14100993    89272  Regular customer         21
18731205   118562  Regular customer         17
32374178   205802  Regular customer         28
22338009   141878    Loyal customer         47
11026392    69858      New customer          9
950820       6147      New customer          9
28959149   183981    Loyal customer         99
17588148   111207  Regular customer         11
25360178   160989      New customer          8
11031671    69880  Regular customer         40
4927343     31379  Regular customer         32
543024       3616      New customer          6
9112261     57785  Regular customer         11
5324322     33831    Loyal customer         59
25288917   160550    Loyal customer         42
333536       2245    Loyal customer         41
3217249     20670  Regular customer         17
15833764   100175  Regular customer         30
7876858     49969      New customer         10
26794615   170365  Regular customer         36
9081166     57548  Regular customer         16
4967127     31632    Loyal customer         45
4289886     27262  Regular customer         34
12974529    82079  Regular customer         22
26569986   168947      New customer          8
3806602     24158  Regular customer         33
10823469    68589  Regular customer         14

In [ ]:
#export dataframe 
df.to_pickle(os.path.join(path, '02_Data', 'Prepared_data', 'full_merged4.pkl'))